import { useEffect, useState, type ReactNode } from "react"
import { AnimatePresence, motion, useReducedMotion } from "motion/react"
import { Activity, ArrowRight, BarChart3, BookOpen, Boxes, Camera, CheckCircle2, ChevronRight, Code2, FlaskConical, Github, GraduationCap, Layers3, Menu, Play, Sparkles, Target, X, Zap } from "lucide-react"
import { Button } from "@/components/ui/button"
import ReliabilityLab from "@/features/reliability-lab/ReliabilityLab"
import { cn } from "@/lib/utils"

const nav=[['Live tracker','/live'],['Learn','/teaching'],['Lab','/lab'],['Research','/writeup'],['Results','/benchmark'],['Docs','/docs/']]

function Shell({children}:{children:ReactNode}){
  const [menu,setMenu]=useState(false)
  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-5">
      <div className="mx-auto flex h-16 max-w-7xl items-center rounded-2xl border border-white/80 bg-white/82 px-4 shadow-[0_10px_40px_-20px_rgba(30,41,59,.35)] backdrop-blur-xl sm:px-5">
        <a href="/" className="group flex items-center gap-3 font-semibold tracking-tight"><img src="/visiontrack-mark.svg?v=3" alt="" className="size-9 rounded-xl shadow-md shadow-indigo-200"/><span>VisionTrack</span></a><a href="/writeup" className="ml-3 hidden rounded-full border border-indigo-100 bg-indigo-50 px-2.5 py-1 font-mono text-[9px] font-semibold uppercase tracking-wider text-indigo-600 transition hover:border-indigo-200 hover:bg-indigo-100 sm:inline">Open research</a>
        <nav className="ml-auto hidden items-center gap-1 md:flex">{nav.map(([label,href])=><a key={href} href={href} className={cn('rounded-lg px-3 py-2 text-sm font-medium text-muted-foreground transition hover:bg-secondary hover:text-foreground',location.pathname===href&&'bg-secondary text-primary')}>{label}</a>)}</nav>
        <Button asChild size="sm" className="ml-3 hidden lg:inline-flex"><a href="/live"><Play className="size-3.5 fill-current"/>Try it live</a></Button>
        <button aria-label="Toggle navigation" onClick={()=>setMenu(!menu)} className="ml-auto grid size-10 place-items-center rounded-xl text-muted-foreground hover:bg-secondary md:hidden">{menu?<X className="size-5"/>:<Menu className="size-5"/>}</button>
      </div>
      <AnimatePresence>{menu&&<motion.nav initial={{height:0,opacity:0,y:-8}} animate={{height:'auto',opacity:1,y:0}} exit={{height:0,opacity:0,y:-8}} className="mx-auto mt-2 max-w-7xl overflow-hidden rounded-2xl border border-white/80 bg-white/95 shadow-xl backdrop-blur-xl md:hidden"><div className="grid gap-1 p-3">{nav.map(([label,href])=><a key={href} href={href} className="rounded-xl px-4 py-3 text-sm font-medium hover:bg-secondary">{label}</a>)}</div></motion.nav>}</AnimatePresence>
    </header>
    <main>{children}</main>
    <footer className="border-t border-border bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 text-sm text-muted-foreground sm:flex-row sm:items-center lg:px-8"><span className="font-semibold text-foreground">VisionTrack</span><span>Open, explainable multi-object tracking.</span><span className="sm:ml-auto">MIT · 479 tests</span><a href="https://github.com/hulagerushikesh/visiontrack" aria-label="GitHub" className="transition hover:text-primary"><Github className="size-4"/></a></div></footer>
  </div>
}

function Reveal({children,className='',delay=0}:{children:ReactNode,className?:string,delay?:number}){const reduce=useReducedMotion();return <motion.div initial={reduce?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-60px'}} transition={{duration:.55,delay,ease:[.22,1,.36,1]}} className={className}>{children}</motion.div>}
function Eyebrow({children}:{children:ReactNode}){return <p className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50/80 px-3 py-1.5 font-mono text-[10px] font-semibold uppercase tracking-[.16em] text-primary"><Sparkles className="size-3"/>{children}</p>}

function TrackerStage(){
 const reduce=useReducedMotion();const [frame,setFrame]=useState(184)
 useEffect(()=>{if(reduce)return;const timer=window.setInterval(()=>setFrame(value=>(value+1)%10000),700);return()=>window.clearInterval(timer)},[reduce])
 const stages=['DETECT','PREDICT','ASSOCIATE','CONFIRM'];const stage=stages[frame%stages.length]
 return <div aria-label="Simulated tracking pipeline preview" className="relative aspect-[16/9] overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#050808] shadow-2xl shadow-black/40">
  <div className="flex h-10 items-center border-b border-white/10 px-4"><div className="flex gap-1.5"><i className="size-2 rounded-full bg-white/15"/><i className="size-2 rounded-full bg-white/15"/><i className="size-2 rounded-full bg-primary/70"/></div><span className="ml-auto font-mono text-[9px] tracking-[.15em] text-primary">SIMULATED · PIPELINE PREVIEW</span></div>
  <div className="absolute inset-x-0 bottom-0 top-10 grid-lines opacity-60"/><motion.div className="absolute left-[14%] top-[34%] h-[31%] w-[16%] border border-primary bg-primary/5" animate={{x:[0,22,-4,0],y:[0,-8,7,0]}} transition={{duration:8,repeat:Infinity,ease:'linear'}}><span className="absolute -top-5 left-0 bg-primary px-1.5 font-mono text-[9px] font-bold text-black">ID 07 · .94</span></motion.div>
  <motion.div className="absolute right-[20%] top-[24%] h-[40%] w-[19%] border border-sky-400 bg-sky-400/5" animate={{x:[0,-35,-10,0],y:[0,12,-4,0]}} transition={{duration:9,repeat:Infinity,ease:'linear'}}><span className="absolute -top-5 left-0 bg-sky-400 px-1.5 font-mono text-[9px] font-bold text-black">ID 12 · .88</span></motion.div>
  <div className="absolute bottom-4 left-4 right-4 flex items-end justify-between"><div><p className="font-mono text-[10px] text-white/45">FRAME {String(frame).padStart(4,'0')} · {stage}</p><p className="font-mono text-xs text-white/80">2 ACTIVE TRACKS</p></div><div className="flex items-end gap-1">{[4,7,5,11,8,15,9,12].map((h,i)=><motion.i key={i} className="w-1 rounded-full bg-primary/70" animate={{height:[h,h+8,h]}} transition={{duration:1.4,repeat:Infinity,delay:i*.1}} style={{height:h}}/>)}</div></div>
 </div>}

function Home(){
  const paths=[
    {tag:'TRY IT',title:'Track from your camera',text:'Run the tracker privately in your browser. Nothing is uploaded.',href:'/live',cta:'Open live tracker',icon:Camera,color:'from-indigo-500 to-blue-500'},
    {tag:'UNDERSTAND IT',title:'Learn how identity persists',text:'Follow one detection through motion, matching, and lifecycle decisions.',href:'/teaching',cta:'Start learning',icon:BookOpen,color:'from-cyan-500 to-sky-500'},
    {tag:'VERIFY IT',title:'Explore measured results',text:'Inspect real benchmarks, failure cases, and honest negative findings.',href:'/benchmark',cta:'View evidence',icon:BarChart3,color:'from-emerald-500 to-teal-500'}
  ]
  const steps=[['01','Detect','Your detector finds objects in each frame.',Boxes],['02','Predict','Motion estimates where every object moves next.',Activity],['03','Associate','Evidence links detections to existing identities.',Layers3],['04','Measure','Failures are reproduced, classified, and compared.',Target]]
  return <>
    <section className="relative pt-32 lg:pt-40"><div className="orb -left-52 -top-24 bg-indigo-300/35"/><div className="orb -right-64 top-20 bg-cyan-200/40"/><div className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:px-8 lg:pb-28">
      <Reveal><div><Eyebrow>Open tracking research · built in public</Eyebrow><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[5.25rem]">See motion.<br/><span className="gradient-text">Keep identity.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">VisionTrack is an explainable multi-object tracking system for people, vehicles, and objects. Test it live, understand every decision, and verify the evidence behind it.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg"><a href="/live"><Play className="size-4 fill-current"/>Try your camera</a></Button><Button asChild size="lg" variant="outline"><a href="/teaching">Explore the project <ArrowRight className="size-4"/></a></Button></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">{['Runs locally','Open source','Measured on real data'].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-500"/>{x}</span>)}</div></div></Reveal>
      <Reveal delay={.12}><div className="relative"><div className="absolute -inset-5 -z-10 rounded-[2rem] bg-gradient-to-br from-indigo-200/60 via-cyan-100/30 to-emerald-100/60 blur-2xl"/><TrackerStage/><div className="mt-4 flex flex-wrap items-center justify-between gap-2 font-mono text-[10px] uppercase tracking-widest text-muted-foreground"><span>Illustrative data</span><span>Explainable core</span><a href="/live" className="font-semibold text-primary transition hover:text-indigo-700">Open real tracker →</a></div></div></Reveal>
    </div></section>

    <section className="border-y border-border/80 bg-white/70"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-border px-5 sm:grid-cols-4 sm:divide-y-0 lg:px-8">{[['369','tests passing'],['1.4e−3','HOTA parity'],['−13%','fewer ID switches'],['294+','FPS at 64 objects']].map(([n,l])=><div className="px-5 py-7 sm:py-8" key={l}><p className="gradient-text text-2xl font-bold tracking-tight sm:text-3xl">{n}</p><p className="mt-1 text-xs font-medium text-muted-foreground">{l}</p></div>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-28"><Reveal><div className="mx-auto max-w-3xl text-center"><Eyebrow>Choose your path</Eyebrow><h2 className="text-balance text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Start with what you need.</h2><p className="mt-5 text-lg leading-8 text-muted-foreground">No maze of pages. Try the system, learn the mechanics, or inspect the results.</p></div></Reveal><div className="mt-14 grid gap-5 md:grid-cols-3">{paths.map((p,i)=><Reveal delay={i*.07} key={p.title}><a href={p.href} className="mesh-card group flex h-full min-h-[340px] flex-col rounded-[1.75rem] border border-white p-7 ring-1 ring-slate-200/70 transition duration-300 hover:-translate-y-1.5 hover:ring-indigo-200"><div className={cn('grid size-12 place-items-center rounded-2xl bg-gradient-to-br text-white shadow-lg',p.color)}><p.icon className="size-5"/></div><span className="mt-10 font-mono text-[10px] font-semibold tracking-[.17em] text-primary">{p.tag}</span><h3 className="mt-3 text-2xl font-semibold tracking-tight">{p.title}</h3><p className="mt-3 leading-7 text-muted-foreground">{p.text}</p><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-semibold text-primary">{p.cta}<ArrowRight className="size-4 transition group-hover:translate-x-1"/></span></a></Reveal>)}</div></section>

    <section className="relative overflow-hidden border-y border-indigo-100/70 bg-gradient-to-br from-indigo-50 via-white to-cyan-50"><div className="soft-grid absolute inset-0"/><div className="relative mx-auto max-w-7xl px-5 py-24 lg:px-8"><Reveal><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Eyebrow>How it works</Eyebrow><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-5xl">From boxes to reliable paths.</h2></div><p className="max-w-2xl text-lg leading-8 text-muted-foreground">VisionTrack separates detection from identity logic, so every part can be tested, replaced, and measured without hiding behind a black box.</p></div></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map(([n,title,text,Icon],i)=><Reveal delay={i*.06} key={String(title)}><div className="h-full rounded-2xl border border-white bg-white/80 p-6 shadow-sm backdrop-blur"><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-primary">{n as string}</span><Icon className="size-5 text-indigo-400"/></div><h3 className="mt-8 text-lg font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text as string}</p></div></Reveal>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-28"><Reveal><div className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-8 text-white shadow-2xl shadow-indigo-950/20 sm:p-12 lg:p-16"><div className="orb -right-28 -top-40 bg-cyan-400/20"/><div className="relative grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><Eyebrow>Research, not marketing</Eyebrow><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-5xl">We measure what helps—and what does not.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/65">Appearance, learned motion, and uncertainty are tested through controlled ablations. Negative results stay visible because trustworthy systems are built from evidence.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild><a href="/writeup">Read the research <ArrowRight className="size-4"/></a></Button><Button asChild variant="outline"><a href="/benchmark" className="border-white/15 bg-white/5 text-white hover:bg-white/10">Explore benchmarks</a></Button></div></div><div className="grid gap-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><FlaskConical className="size-5 text-cyan-300"/><p className="mt-4 font-semibold">Controlled experiments</p><p className="mt-2 text-sm leading-6 text-white/55">Same detections. One changed variable. Paired evidence.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><Zap className="size-5 text-emerald-300"/><p className="mt-4 font-semibold">Verified fast runtime</p><p className="mt-2 text-sm leading-6 text-white/55">Accepted behavior crosses a parity gate into C++.</p></div></div></div></div></Reveal></section>
  </>
}

const modules=[{n:'01',tag:'PROJECT',title:'Learn VisionTrack',text:'Trace geometry, Kalman prediction, Hungarian assignment, ByteTrack, evaluation, and the four research questions in repository order.',meta:'8–12 hours',href:'/study',icon:BookOpen},{n:'02',tag:'FIELD',title:'Computer vision roadmap',text:'Move from mathematical foundations and classical vision through deep learning, production systems, and original research.',meta:'Self-paced',href:'/roadmap',icon:GraduationCap},{n:'03',tag:'SYSTEMS',title:'Learn VisionTrack C++',text:'Understand CMake, Eigen, pybind11, parity, profiling, packaging, and why performance claims must survive measurement.',meta:'4–6 hours',href:'https://github.com/hulagerushikesh/visiontrack-cpp/tree/main/learning',icon:Code2}]
function Teaching(){return <div className="mx-auto max-w-7xl px-5 pb-28 pt-32 lg:px-8 lg:pt-40"><Reveal><Eyebrow>Learning lab</Eyebrow><div className="max-w-4xl"><h1 className="text-balance text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Understand the system.<br/><span className="text-muted-foreground">Then change it.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Three guided paths use the real project as the textbook—from one tracking frame to the wider computer-vision field and its C++ performance twin.</p></div></Reveal><div className="mt-16 grid gap-5 lg:grid-cols-3">{modules.map((m,i)=><Reveal key={m.n} delay={i*.08}><a href={m.href} className="group flex h-full min-h-[390px] flex-col rounded-[1.75rem] border border-border bg-card p-7 transition hover:-translate-y-1 hover:border-primary/40"><div className="flex items-start justify-between"><span className="font-mono text-xs tracking-[.15em] text-primary">{m.n} · {m.tag}</span><m.icon className="size-5 text-muted-foreground transition group-hover:text-primary"/></div><h2 className="mt-16 text-2xl font-semibold tracking-tight">{m.title}</h2><p className="mt-4 leading-7 text-muted-foreground">{m.text}</p><div className="mt-auto flex items-center justify-between border-t border-border pt-6 text-sm"><span className="text-muted-foreground">{m.meta}</span><span className="flex items-center gap-1 font-semibold text-primary">Open <ChevronRight className="size-4 transition group-hover:translate-x-1"/></span></div></a></Reveal>)}</div><Reveal className="mt-20"><div className="grid gap-8 rounded-[1.75rem] border border-border p-8 lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div><Eyebrow>Builder quickstart</Eyebrow><h2 className="text-3xl font-semibold tracking-tight">One public contract.</h2><p className="mt-4 leading-7 text-muted-foreground">Bring detections, call update once per frame, and receive stable track IDs.</p></div><pre className="overflow-x-auto rounded-2xl bg-[#07100e] p-6 font-mono text-xs leading-6 text-white/75"><code><span className="text-primary">from</span> visiontrack <span className="text-primary">import</span> ByteTracker, Detection{`\n\n`}tracker = ByteTracker(){`\n`}tracks = tracker.update(detections){`\n\n`}<span className="text-white/35"># identity remains stable across frames</span>{`\n`}print([t.track_id <span className="text-primary">for</span> t <span className="text-primary">in</span> tracks])</code></pre></div></Reveal></div>}

function Video(){return <div className="mx-auto max-w-7xl px-5 pb-28 pt-32 lg:px-8 lg:pt-40"><Reveal><Eyebrow>Real footage · 300 frames</Eyebrow><div className="grid gap-8 lg:grid-cols-2 lg:items-end"><h1 className="text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Same tracker.<br/><span className="text-muted-foreground">Real streets.</span></h1><p className="max-w-xl text-lg leading-8 text-muted-foreground">YOLOX detections meet the same from-scratch Kalman, Hungarian, and ByteTrack pipeline—107 identities across a crowded Bangkok intersection.</p></div></Reveal><Reveal className="mt-14"><div className="overflow-hidden rounded-[1.75rem] border border-border bg-black shadow-2xl"><video controls autoPlay muted loop playsInline preload="metadata" poster="/street_tracking_poster.jpg" className="aspect-video w-full"><source src="/street_tracking.mp4" type="video/mp4"/></video></div></Reveal><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['300','frames'],['107','unique IDs'],['6','street classes'],['0','tracking libraries']].map(([n,l],i)=><Reveal key={l} delay={i*.05}><div className="rounded-2xl border border-border bg-card p-5"><p className="text-3xl font-semibold">{n}</p><p className="mt-1 text-sm text-muted-foreground">{l}</p></div></Reveal>)}</div></div>}

function NotFound(){return <div className="grid min-h-[80vh] place-items-center px-5 pt-16 text-center"><div><Boxes className="mx-auto size-10 text-primary"/><h1 className="mt-5 text-4xl font-semibold">Route not found</h1><Button asChild className="mt-7"><a href="/">Return home</a></Button></div></div>}
function App(){const path=location.pathname.replace(/\/$/,'')||'/';const page=path==='/'?<Home/>:path==='/teaching'?<Teaching/>:path==='/video'?<Video/>:path==='/lab'?<ReliabilityLab/>:<NotFound/>;return <Shell><AnimatePresence mode="wait"><motion.div key={path} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.2}}>{page}</motion.div></AnimatePresence></Shell>}
export default App
