import { useEffect, useState, type ReactNode } from "react"
import { AnimatePresence, motion, useReducedMotion } from "motion/react"
import { ArrowRight, BarChart3, BookOpen, Boxes, Camera, ChevronRight, Code2, Github, GraduationCap, Menu, Moon, Play, Route, Sun, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

const nav=[['Live','/live'],['Learn','/teaching'],['Demo','/demo'],['Research','/writeup'],['Benchmarks','/benchmark'],['Docs','/docs/']]
const legacy=new Set(['/live','/demo','/writeup','/benchmark','/docs/'])

function Shell({children}:{children:ReactNode}){
  const [dark,setDark]=useState(()=>localStorage.getItem('vt-theme')!=='light')
  const [menu,setMenu]=useState(false)
  useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('vt-theme',dark?'dark':'light')},[dark])
  return <div className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-border/60 bg-background/75 backdrop-blur-xl">
      <div className="mx-auto flex h-16 max-w-7xl items-center px-5 lg:px-8">
        <a href="/" className="group flex items-center gap-3 font-semibold tracking-tight"><img src="/visiontrack-mark.svg" alt="" className="size-8 rounded-xl shadow-sm"/>VisionTrack <span className="hidden rounded-full bg-secondary px-2 py-0.5 font-mono text-[10px] font-medium text-muted-foreground sm:inline">NumPy · MOT</span></a>
        <nav className="ml-auto hidden items-center gap-1 md:flex">{nav.map(([label,href])=><a key={href} href={href} className={cn('rounded-full px-3 py-2 text-sm text-muted-foreground transition hover:bg-secondary hover:text-foreground',location.pathname===href&&'bg-secondary text-foreground')}>{label}</a>)}</nav>
        <button aria-label="Toggle theme" onClick={()=>setDark(!dark)} className="ml-2 grid size-9 place-items-center rounded-full text-muted-foreground hover:bg-secondary hover:text-foreground">{dark?<Sun className="size-4"/>:<Moon className="size-4"/>}</button>
        <button aria-label="Toggle navigation" onClick={()=>setMenu(!menu)} className="ml-1 grid size-9 place-items-center rounded-full md:hidden">{menu?<X className="size-5"/>:<Menu className="size-5"/>}</button>
      </div>
      <AnimatePresence>{menu&&<motion.nav initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-border bg-background md:hidden"><div className="grid gap-1 p-4">{nav.map(([label,href])=><a href={href} className="rounded-xl px-4 py-3 text-sm hover:bg-secondary">{label}</a>)}</div></motion.nav>}</AnimatePresence>
    </header>
    <main>{children}</main>
    <footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 text-sm text-muted-foreground sm:flex-row sm:items-center lg:px-8"><span className="font-semibold text-foreground">VisionTrack</span><span>Built from first principles. Measured without spin.</span><span className="sm:ml-auto">MIT · 349 tests</span><a href="https://github.com/hulagerushikesh/visiontrack" aria-label="GitHub"><Github className="size-4"/></a></div></footer>
  </div>
}

function Reveal({children,className='',delay=0}:{children:ReactNode,className?:string,delay?:number}){const reduce=useReducedMotion();return <motion.div initial={reduce?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-60px'}} transition={{duration:.55,delay,ease:[.22,1,.36,1]}} className={className}>{children}</motion.div>}
function Eyebrow({children}:{children:ReactNode}){return <p className="mb-5 flex items-center gap-2 font-mono text-xs font-semibold uppercase tracking-[.18em] text-primary"><span className="h-px w-7 bg-primary"/>{children}</p>}

function TrackerStage(){return <div className="relative aspect-[16/9] overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#050808] shadow-2xl shadow-black/40">
  <div className="flex h-10 items-center border-b border-white/10 px-4"><div className="flex gap-1.5"><i className="size-2 rounded-full bg-white/15"/><i className="size-2 rounded-full bg-white/15"/><i className="size-2 rounded-full bg-primary/70"/></div><span className="ml-auto font-mono text-[9px] tracking-[.15em] text-primary">LIVE · ON DEVICE</span></div>
  <div className="absolute inset-x-0 bottom-0 top-10 grid-lines opacity-60"/><motion.div className="absolute left-[14%] top-[34%] h-[31%] w-[16%] border border-primary bg-primary/5" animate={{x:[0,22,-4,0],y:[0,-8,7,0]}} transition={{duration:8,repeat:Infinity,ease:'linear'}}><span className="absolute -top-5 left-0 bg-primary px-1.5 font-mono text-[9px] font-bold text-black">ID 07 · .94</span></motion.div>
  <motion.div className="absolute right-[20%] top-[24%] h-[40%] w-[19%] border border-sky-400 bg-sky-400/5" animate={{x:[0,-35,-10,0],y:[0,12,-4,0]}} transition={{duration:9,repeat:Infinity,ease:'linear'}}><span className="absolute -top-5 left-0 bg-sky-400 px-1.5 font-mono text-[9px] font-bold text-black">ID 12 · .88</span></motion.div>
  <div className="absolute bottom-4 left-4 right-4 flex items-end justify-between"><div><p className="font-mono text-[10px] text-white/45">FRAME 0184</p><p className="font-mono text-xs text-white/80">2 ACTIVE TRACKS</p></div><div className="flex items-end gap-1">{[4,7,5,11,8,15,9,12].map((h,i)=><motion.i key={i} className="w-1 rounded-full bg-primary/70" animate={{height:[h,h+8,h]}} transition={{duration:1.4,repeat:Infinity,delay:i*.1}} style={{height:h}}/>)}</div></div>
 </div>}

function Home(){const useCases=[['Retail & spaces','Unique visitors, dwell time, and queues—not duplicate frame counts.',BarChart3],['Sports analytics','Per-player paths, spacing, and identity through contact.',Route],['Traffic & mobility','Vehicle flows and turning movements, tracked exactly once.',Camera]];return <>
  <section className="relative pt-32 lg:pt-40"><div className="orb -left-40 top-0 bg-primary/20"/><div className="mx-auto grid max-w-7xl gap-14 px-5 pb-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8">
    <Reveal><div><Eyebrow>Open-source multi-object tracking</Eyebrow><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[.96] tracking-[-.055em] sm:text-7xl lg:text-[5.4rem]">Stable identity,<br/><span className="text-muted-foreground">every frame.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">Follow people, vehicles, or objects through crossings, occlusion, and clutter. A transparent Kalman + Hungarian + ByteTrack core built from scratch—not hidden behind a tracking library.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg"><a href="/live"><Play className="size-4 fill-current"/>Try the live tracker</a></Button><Button asChild size="lg" variant="outline"><a href="/teaching">Learn how it works <ArrowRight className="size-4"/></a></Button></div></div></Reveal>
    <Reveal delay={.12}><TrackerStage/><div className="mt-4 flex flex-wrap justify-between gap-2 font-mono text-[10px] uppercase tracking-widest text-muted-foreground"><span>Nothing uploaded</span><span>Runs in your browser</span><span>0 tracking libraries</span></div></Reveal>
  </div></section>
  <section className="border-y border-border bg-card/50"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-border px-5 sm:grid-cols-4 sm:divide-y-0 lg:px-8">{[['349','tests passing'],['1.4e−3','HOTA parity'],['−13%','MOT17 ID switches'],['0','tracking dependencies']].map(([n,l])=><div className="px-5 py-8" key={l}><p className="text-2xl font-semibold tracking-tight sm:text-3xl">{n}</p><p className="mt-1 text-xs text-muted-foreground">{l}</p></div>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><Reveal><Eyebrow>What it unlocks</Eyebrow><div className="grid gap-7 lg:grid-cols-2"><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Turn a camera into paths, counts, and identities.</h2><p className="max-w-lg self-end text-lg leading-8 text-muted-foreground">Tracking is the layer between raw detections and useful answers. Bring the detector for your domain; VisionTrack keeps the identity logic explainable.</p></div></Reveal><div className="mt-14 grid gap-4 md:grid-cols-3">{useCases.map(([title,desc,Icon],i)=><Reveal delay={i*.07} key={String(title)}><div className="group h-full rounded-3xl border border-border bg-card p-7 transition hover:-translate-y-1 hover:border-primary/35"><div className="mb-12 grid size-11 place-items-center rounded-2xl bg-secondary text-primary"><Icon className="size-5"/></div><h3 className="text-xl font-semibold">{title as string}</h3><p className="mt-3 leading-7 text-muted-foreground">{desc as string}</p></div></Reveal>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 pb-28 lg:px-8"><Reveal><div className="relative overflow-hidden rounded-[2rem] border border-primary/20 bg-[#0a1512] p-8 text-white sm:p-12 lg:p-16"><div className="orb -right-28 -top-40 bg-primary/20"/><Eyebrow>Under the hood</Eyebrow><h2 className="relative max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-5xl">The tracker is the experiment.</h2><p className="relative mt-5 max-w-2xl text-lg leading-8 text-white/60">Every component is independently tested, then used to ask when appearance, learned motion, and calibrated uncertainty actually help. Some answers are honest negatives—that is the point.</p><div className="relative mt-9 flex flex-wrap gap-3"><Button asChild><a href="/writeup">Read the research <ArrowRight className="size-4"/></a></Button><Button asChild variant="outline"><a href="/benchmark" className="border-white/15 bg-white/5 text-white">Explore benchmarks</a></Button></div></div></Reveal></section>
 </>}

const modules=[{n:'01',tag:'PROJECT',title:'Learn VisionTrack',text:'Trace geometry, Kalman prediction, Hungarian assignment, ByteTrack, evaluation, and the four research questions in repository order.',meta:'8–12 hours',href:'/study',icon:BookOpen},{n:'02',tag:'FIELD',title:'Computer vision roadmap',text:'Move from mathematical foundations and classical vision through deep learning, production systems, and original research.',meta:'Self-paced',href:'/roadmap',icon:GraduationCap},{n:'03',tag:'SYSTEMS',title:'Learn VisionTrack C++',text:'Understand CMake, Eigen, pybind11, parity, profiling, packaging, and why performance claims must survive measurement.',meta:'4–6 hours',href:'https://github.com/hulagerushikesh/visiontrack-cpp/tree/main/learning',icon:Code2}]
function Teaching(){return <div className="mx-auto max-w-7xl px-5 pb-28 pt-32 lg:px-8 lg:pt-40"><Reveal><Eyebrow>Learning lab</Eyebrow><div className="max-w-4xl"><h1 className="text-balance text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Understand the system.<br/><span className="text-muted-foreground">Then change it.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Three guided paths use the real project as the textbook—from one tracking frame to the wider computer-vision field and its C++ performance twin.</p></div></Reveal><div className="mt-16 grid gap-5 lg:grid-cols-3">{modules.map((m,i)=><Reveal key={m.n} delay={i*.08}><a href={m.href} className="group flex h-full min-h-[390px] flex-col rounded-[1.75rem] border border-border bg-card p-7 transition hover:-translate-y-1 hover:border-primary/40"><div className="flex items-start justify-between"><span className="font-mono text-xs tracking-[.15em] text-primary">{m.n} · {m.tag}</span><m.icon className="size-5 text-muted-foreground transition group-hover:text-primary"/></div><h2 className="mt-16 text-2xl font-semibold tracking-tight">{m.title}</h2><p className="mt-4 leading-7 text-muted-foreground">{m.text}</p><div className="mt-auto flex items-center justify-between border-t border-border pt-6 text-sm"><span className="text-muted-foreground">{m.meta}</span><span className="flex items-center gap-1 font-semibold text-primary">Open <ChevronRight className="size-4 transition group-hover:translate-x-1"/></span></div></a></Reveal>)}</div><Reveal className="mt-20"><div className="grid gap-8 rounded-[1.75rem] border border-border p-8 lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div><Eyebrow>Builder quickstart</Eyebrow><h2 className="text-3xl font-semibold tracking-tight">One public contract.</h2><p className="mt-4 leading-7 text-muted-foreground">Bring detections, call update once per frame, and receive stable track IDs.</p></div><pre className="overflow-x-auto rounded-2xl bg-[#07100e] p-6 font-mono text-xs leading-6 text-white/75"><code><span className="text-primary">from</span> visiontrack <span className="text-primary">import</span> ByteTracker, Detection{`\n\n`}tracker = ByteTracker(){`\n`}tracks = tracker.update(detections){`\n\n`}<span className="text-white/35"># identity remains stable across frames</span>{`\n`}print([t.track_id <span className="text-primary">for</span> t <span className="text-primary">in</span> tracks])</code></pre></div></Reveal></div>}

function Video(){return <div className="mx-auto max-w-7xl px-5 pb-28 pt-32 lg:px-8 lg:pt-40"><Reveal><Eyebrow>Real footage · 300 frames</Eyebrow><div className="grid gap-8 lg:grid-cols-2 lg:items-end"><h1 className="text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Same tracker.<br/><span className="text-muted-foreground">Real streets.</span></h1><p className="max-w-xl text-lg leading-8 text-muted-foreground">YOLOX detections meet the same from-scratch Kalman, Hungarian, and ByteTrack pipeline—107 identities across a crowded Bangkok intersection.</p></div></Reveal><Reveal className="mt-14"><div className="overflow-hidden rounded-[1.75rem] border border-border bg-black shadow-2xl"><video controls autoPlay muted loop playsInline preload="metadata" poster="/street_tracking_poster.jpg" className="aspect-video w-full"><source src="/street_tracking.mp4" type="video/mp4"/></video></div></Reveal><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['300','frames'],['107','unique IDs'],['6','street classes'],['0','tracking libraries']].map(([n,l],i)=><Reveal key={l} delay={i*.05}><div className="rounded-2xl border border-border bg-card p-5"><p className="text-3xl font-semibold">{n}</p><p className="mt-1 text-sm text-muted-foreground">{l}</p></div></Reveal>)}</div></div>}

function NotFound(){return <div className="grid min-h-[80vh] place-items-center px-5 pt-16 text-center"><div><Boxes className="mx-auto size-10 text-primary"/><h1 className="mt-5 text-4xl font-semibold">Route not found</h1><Button asChild className="mt-7"><a href="/">Return home</a></Button></div></div>}
function App(){const path=location.pathname.replace(/\/$/,'')||'/';const page=path==='/'?<Home/>:path==='/teaching'?<Teaching/>:path==='/video'?<Video/>:<NotFound/>;return <Shell><AnimatePresence mode="wait"><motion.div key={path} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.2}}>{page}</motion.div></AnimatePresence></Shell>}
export default App
